tailscale_extra_args: "--advertise-exit-node --accept-routes"
# tailscale_authkey: never stored here â€” pass via -e at runtime (only for re-registration)

traefik_tailscale_ip: "100.92.78.42"

qbittorrent_torrent_tailscale_ip: "100.122.130.88"

torrent_port: 6881
http_port: 80
https_port: 443
public_interface: "eth0"
sysctl_config_file: "/etc/sysctl.d/99-tailscale.conf"
