---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Dashboard
  - homer/applicationset.yaml

  # Media Server & UI
  - jellyfin/applicationset.yaml
  - jellyseerr/applicationset.yaml

  # Content Management (*arr stack)
  - sonarr/applicationset.yaml
  - radarr/applicationset.yaml
  - bazarr/applicationset.yaml
  - prowlarr/applicationset.yaml

  # Download & Tools
  - qbittorrent/applicationset.yaml
  - flaresolverr/applicationset.yaml

  # Storage
  - shared-storage/applicationset.yaml
