---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr
  namespace: prod-media
spec:
  entryPoints:
    - websecure
  routes:
    # Authentik outpost path (higher priority, no auth middleware)
    - match: Host(`sonarr.st0rmingbr4in.com`) && PathPrefix(`/outpost.goauthentik.io`)
      kind: Rule
      priority: 100
      services:
        - name: authentik-server
          namespace: prod-infra
          #port: 9000
    # Main Sonarr application (with Authentik forward auth)
    - match: Host(`sonarr.st0rmingbr4in.com`)
      kind: Rule
      priority: 10
      middlewares:
        - name: authentik-forward-auth
          namespace: prod-infra
      services:
        - name: sonarr
          #port: 10095
