all:
  children:
    inlet:
      hosts:
        inlet.st0rmingbr4in.com:
          ansible_host: 64.226.113.229
          ansible_user: root
          tailscale_ip: "100.123.88.118"
    k3s_cluster:
      children:
        server:
          hosts:
            k3s-clusterv2-server1.vms.st0rmingbr4in.com:
              k3s_control_node: true
        agent:
          hosts:
            k3s-clusterv2-node1.vms.st0rmingbr4in.com:
              k3s_control_node: false
