---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Certificate Management
  - cert-manager/applicationset.yaml
  - cert-manager-selfsigned-issuer/applicationset.yaml
  - cert-manager-letsencrypt-issuer/applicationset.yaml

  # Load Balancing & Networking
  - tailscale-operator/applicationset.yaml
  - traefik/applicationset.yaml

  # Secret Management
  - vault/applicationset.yaml
  - vault-secrets-operator/applicationset.yaml

  # Monitoring & DNS
  - datadog/applicationset.yaml
  - pihole/applicationset.yaml

  # Authentication
  - authentik/applicationset.yaml
